# -*- coding: utf-8 -*-
"""Ai-lab task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XsPXpDf2hG8EMYjMC6rcypmxRESUQ-ns
"""

class ModelReflexAgent:
    def __init__(self, desired_temperature):
        self.desired_temperature = desired_temperature
        self.status = 'off'

    def perceive(self, current_temperature):
        return current_temperature

    def act(self, current_temperature):
        if current_temperature < self.desired_temperature and self.status == "off":
            action = "Turn on heater"
            self.status = 'on'
        else:
            action = "Turn off heater"
            self.status = 'off'
        return action

# Simulating different rooms with different current temperatures
rooms = {
    "Living Room": 18,
    "Bedroom": 22,
    "Kitchen": 20,
    "Bathroom": 24
}

# Desired temperature for all rooms
desired_temperature = 22
agent = ModelReflexAgent(desired_temperature)

# Run the agent for each room
for room, temperature in rooms.items():
    action = agent.act(temperature)
    print(f"{room}: Current temperature = {temperature}°C. {action}.Heater status: {agent.status}.")